name: Publish to VS Code Marketplace

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: npm install

    # Step 4: Increment version in package.json
    - name: Increment version
      id: version
      run: |
        node -e "
        const fs = require('fs');
        const path = './package.json';
        const package = JSON.parse(fs.readFileSync(path));
        const [major, minor, patch] = package.version.split('.').map(Number);
        package.version = [major, minor, patch + 1].join('.');
        fs.writeFileSync(path, JSON.stringify(package, null, 2));
        console.log(`::set-output name=version::${package.version}`);
        "
        
      # Step 5: Commit the version bump
    - name: Commit version bump
      env:
        GITHUB_TOKEN: ${{ secrets.ALIAS_AI_GIT_ACTIONS }}
        GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}
        GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
      run: |
        git config user.name "${GIT_USER_NAME}"
        git config user.email "${GIT_EMAIL}"
        git remote remove origin
        git remote add origin https://${GITHUB_TOKEN}@github.com/${{ github.repository }}
        git add package.json
        git commit -m "Bump version to ${{ steps.version.outputs.version }}"

        echo "GITHUB_TOKEN is set: ${GITHUB_TOKEN:0:5}******"
        echo "GIT_USER_NAME: ${GIT_USER_NAME:0:3}"
        echo "GIT_EMAIL: ${GIT_EMAIL:0:3}"
        echo "Repository: ${{ github.repository }}"
        echo "New Version: ${{ steps.version.outputs.version }}"

        git push --set-upstream origin main

    # Step 6: Package and publish extension
    - name: Publish to VS Code Marketplace
      run: |
        npm install -g @vscode/vsce
        vsce package
        vsce publish -p ${{ secrets.ALIAS_AI_PUBLISH_TOKEN }}
